import * as Lucide from "lucide-react";

export const Bell = Lucide.Bell;
export const ChartArea = Lucide.ChartArea;
export const ChevronLeft = Lucide.ChevronLeft;
export const ChevronsLeft = Lucide.ChevronsLeft;
export const ChevronRight = Lucide.ChevronRight;
export const ChevronsRight = Lucide.ChevronsRight;
export const Copy = Lucide.Copy;
export const Gem = Lucide.Gem;
export const Languages = Lucide.Languages;
export const List = Lucide.List;
export const LogOut = Lucide.LogOut;
export const MessageCircleMore = Lucide.MessageCircleMore;
export const Moon = Lucide.Moon;
export const MoreHorizontal = Lucide.MoreHorizontal;
export const Settings = Lucide.Settings;
export const SquarePen = Lucide.SquarePen;
export const Sun = Lucide.Sun;
export const Trash2 = Lucide.Trash2;
